### ISSUE TITLE
v1.1.0 breaks the quick example (RDT-352)

### ISSUE THREAD

**Issue by daltonv** [espressif/pytest-embedded#177]
The commit from #172 adds a dependency on pytest-embedded-idf without updating the pytest-embedded package's dependencies.

Now if users are following the quick example in the readme they will be treated to an error like this:
```console
pytest
Traceback (most recent call last):
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190, in console_main
    code = main()
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/daltonv/.pyenv/versions/3.10.2/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/home/daltonv/.pyenv/versions/3.10.2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/daltonv/scratch/pytest_embedded_test/.venv/lib/python3.10/site-packages/pytest_embedded/plugin.py", line 42, in <module>
    from pytest_embedded_idf import CaseTester
ModuleNotFoundError: No module named 'pytest_embedded_idf'
```

The `pytest-embedded/setup.py` file should be modified to explicitly add this new dependency:
```python
REQUIRES = [
    'pytest>=7.0',
    'pexpect>=4.4',
    'pytest_embedded>=1.1.0' # not sure if that exact version is the one needed
]
```

**Comment by hfudev** [comment]
@daltonv Thanks for reporting! will release a bugfix version soon.
